# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Client(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, first_name: str=None, middle_name: str=None, last_name: str=None):  # noqa: E501
        """Client - a model defined in Swagger

        :param first_name: The first_name of this Client.  # noqa: E501
        :type first_name: str
        :param middle_name: The middle_name of this Client.  # noqa: E501
        :type middle_name: str
        :param last_name: The last_name of this Client.  # noqa: E501
        :type last_name: str
        """
        self.swagger_types = {
            'first_name': str,
            'middle_name': str,
            'last_name': str
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'middle_name': 'middleName',
            'last_name': 'lastName'
        }
        self._first_name = first_name
        self._middle_name = middle_name
        self._last_name = last_name

    @classmethod
    def from_dict(cls, dikt) -> 'Client':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The client of this Client.  # noqa: E501
        :rtype: Client
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Client.

        Имя клиента  # noqa: E501

        :return: The first_name of this Client.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Client.

        Имя клиента  # noqa: E501

        :param first_name: The first_name of this Client.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def middle_name(self) -> str:
        """Gets the middle_name of this Client.

        Отчество клиента  # noqa: E501

        :return: The middle_name of this Client.
        :rtype: str
        """
        return self._middle_name

    @middle_name.setter
    def middle_name(self, middle_name: str):
        """Sets the middle_name of this Client.

        Отчество клиента  # noqa: E501

        :param middle_name: The middle_name of this Client.
        :type middle_name: str
        """

        self._middle_name = middle_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Client.

        Фамилия клиента  # noqa: E501

        :return: The last_name of this Client.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Client.

        Фамилия клиента  # noqa: E501

        :param last_name: The last_name of this Client.
        :type last_name: str
        """

        self._last_name = last_name
