# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, otr_id: str=None, file_name: str=None):  # noqa: E501
        """DocumentInfo - a model defined in Swagger

        :param otr_id: The otr_id of this DocumentInfo.  # noqa: E501
        :type otr_id: str
        :param file_name: The file_name of this DocumentInfo.  # noqa: E501
        :type file_name: str
        """
        self.swagger_types = {
            'otr_id': str,
            'file_name': str
        }

        self.attribute_map = {
            'otr_id': 'otrId',
            'file_name': 'fileName'
        }
        self._otr_id = otr_id
        self._file_name = file_name

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The documentInfo of this DocumentInfo.  # noqa: E501
        :rtype: DocumentInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def otr_id(self) -> str:
        """Gets the otr_id of this DocumentInfo.

        Идентификатор одноразовой ссылки  # noqa: E501

        :return: The otr_id of this DocumentInfo.
        :rtype: str
        """
        return self._otr_id

    @otr_id.setter
    def otr_id(self, otr_id: str):
        """Sets the otr_id of this DocumentInfo.

        Идентификатор одноразовой ссылки  # noqa: E501

        :param otr_id: The otr_id of this DocumentInfo.
        :type otr_id: str
        """

        self._otr_id = otr_id

    @property
    def file_name(self) -> str:
        """Gets the file_name of this DocumentInfo.

        Наименование загруженного файла  # noqa: E501

        :return: The file_name of this DocumentInfo.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this DocumentInfo.

        Наименование загруженного файла  # noqa: E501

        :param file_name: The file_name of this DocumentInfo.
        :type file_name: str
        """

        self._file_name = file_name
