# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Organization(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orgname: str=None):  # noqa: E501
        """Organization - a model defined in Swagger

        :param orgname: The orgname of this Organization.  # noqa: E501
        :type orgname: str
        """
        self.swagger_types = {
            'orgname': str
        }

        self.attribute_map = {
            'orgname': 'orgname'
        }
        self._orgname = orgname

    @classmethod
    def from_dict(cls, dikt) -> 'Organization':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The organization of this Organization.  # noqa: E501
        :rtype: Organization
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orgname(self) -> str:
        """Gets the orgname of this Organization.

        Название организации  # noqa: E501

        :return: The orgname of this Organization.
        :rtype: str
        """
        return self._orgname

    @orgname.setter
    def orgname(self, orgname: str):
        """Sets the orgname of this Organization.

        Название организации  # noqa: E501

        :param orgname: The orgname of this Organization.
        :type orgname: str
        """

        self._orgname = orgname
