# coding: utf-8

# flake8: noqa

"""
    API для Навыка

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.__api import _Api
from swagger_client.api.____api import _Api
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.all_task_info import AllTaskInfo
from swagger_client.models.business_process import BusinessProcess
from swagger_client.models.client import Client
from swagger_client.models.client_manager_comment import ClientManagerComment
from swagger_client.models.deal_members_number import DealMembersNumber
from swagger_client.models.document_info import DocumentInfo
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.estate_object import EstateObject
from swagger_client.models.organization import Organization
from swagger_client.models.success_response import SuccessResponse
from swagger_client.models.task_info import TaskInfo
from swagger_client.models.task_initiator import TaskInitiator
from swagger_client.models.task_request import TaskRequest
from swagger_client.models.task_request_task_info import TaskRequestTaskInfo
