# coding: utf-8

"""
    API для Навыка

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DocumentInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'otr_id': 'str',
        'file_name': 'str'
    }

    attribute_map = {
        'otr_id': 'otrId',
        'file_name': 'fileName'
    }

    def __init__(self, otr_id=None, file_name=None):  # noqa: E501
        """DocumentInfo - a model defined in Swagger"""  # noqa: E501
        self._otr_id = None
        self._file_name = None
        self.discriminator = None
        if otr_id is not None:
            self.otr_id = otr_id
        if file_name is not None:
            self.file_name = file_name

    @property
    def otr_id(self):
        """Gets the otr_id of this DocumentInfo.  # noqa: E501

        Идентификатор одноразовой ссылки  # noqa: E501

        :return: The otr_id of this DocumentInfo.  # noqa: E501
        :rtype: str
        """
        return self._otr_id

    @otr_id.setter
    def otr_id(self, otr_id):
        """Sets the otr_id of this DocumentInfo.

        Идентификатор одноразовой ссылки  # noqa: E501

        :param otr_id: The otr_id of this DocumentInfo.  # noqa: E501
        :type: str
        """

        self._otr_id = otr_id

    @property
    def file_name(self):
        """Gets the file_name of this DocumentInfo.  # noqa: E501

        Наименование загруженного файла  # noqa: E501

        :return: The file_name of this DocumentInfo.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this DocumentInfo.

        Наименование загруженного файла  # noqa: E501

        :param file_name: The file_name of this DocumentInfo.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
