openapi: 3.0.1
info:
  title: API для Навыка
  version: 1.0.0
servers:
- url: /
paths:
  /SalutClientRequest:
    post:
      tags:
      - Создание заявки
      operationId: salut_client_request_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/taskRequest'
        required: true
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
        "400":
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-openapi-router-controller: swagger_server.controllers.создание_заявкиcontroller
  /taskInfo/all/{initiatorID}:
    get:
      tags:
      - "Просмотр заявок, созданных инициатором"
      operationId: task_info_all_initiator_idget
      parameters:
      - name: initiatorID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 50
          type: string
      responses:
        "200":
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/allTaskInfo'
        "400":
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-openapi-router-controller: "swagger_server.controllers.просмотр_заявок,_со\
        зданных_инициаторомcontroller"
components:
  schemas:
    taskInitiator:
      required:
      - externalId
      - initiatorEmail
      - initiatorID
      - source
      type: object
      properties:
        externalId:
          maxLength: 254
          type: string
          description: Идентификатор заявки в источнике заявки (Номер КД)
          example: externalId_1
        source:
          maxLength: 10
          type: string
          description: Источник заявки(константа-SALUT)
        tbName:
          maxLength: 2
          type: string
          description: Территориальный Банк
          example: "99"
        initiatorEmail:
          maxLength: 50
          type: string
          description: Email инициатора (корпоративный)
        initiatorID:
          maxLength: 254
          type: string
          description: ID пользователя
      description: Информация об инициаторе заявки
    businessProcess:
      required:
      - category
      - type
      type: object
      properties:
        type:
          maxLength: 32
          type: string
          description: Тип запроса
          example: TP_6
        category:
          maxLength: 32
          type: string
          description: Категория запроса
          example: RQ_4203
      description: Информация о типе и категории запроса
    dealMembersNumber:
      minimum: 0
      type: integer
      description: Информация о количестве участников сделки
    client:
      type: object
      properties:
        firstName:
          maxLength: 84
          type: string
          description: Имя клиента
          example: Иван
        middleName:
          maxLength: 84
          type: string
          description: Отчество клиента
          example: Иванович
        lastName:
          maxLength: 84
          type: string
          description: Фамилия клиента
          example: Иванов
      description: Информация о клиенте
    organization:
      type: object
      properties:
        orgname:
          maxLength: 254
          type: string
          description: Название организации
      description: Информация об организации
    estateObject:
      type: object
      properties:
        objectType:
          maxLength: 50
          type: string
          description: Тип объекта
        objectCost:
          multipleOf: 0.01
          maximum: 99999999999999.98
          minimum: 0
          type: number
          description: Стоимость объекта недвижимости
        tbObjectName:
          maxLength: 2
          type: string
          description: Территориальный Банк ОН
          example: "99"
        objectRegionCode:
          maxLength: 32
          type: string
          description: Регион объекта недвижимости
        currency:
          maxLength: 10
          type: string
          description: Валюта (const=643)
      description: Информация об объекте недвижимости
    clientManagerComment:
      maxLength: 1000
      type: string
      description: Комментарий КМ
    documentInfo:
      type: object
      properties:
        otrId:
          type: string
          description: Идентификатор одноразовой ссылки
        fileName:
          type: string
          description: Наименование загруженного файла
      description: Данные для выгрузки файла
    taskRequest:
      required:
      - businessProcess
      - taskInitiator
      type: object
      properties:
        taskInitiator:
          $ref: '#/components/schemas/taskInitiator'
        businessProcess:
          $ref: '#/components/schemas/businessProcess'
        taskInfo:
          $ref: '#/components/schemas/taskRequest_taskInfo'
        clientManagerComment:
          $ref: '#/components/schemas/clientManagerComment'
        documentsInfo:
          type: array
          description: Данные для выгрузки файла
          items:
            $ref: '#/components/schemas/documentInfo'
      description: ""
    successResponse:
      required:
      - status
      type: object
      properties:
        status:
          type: string
          example: SUCCESS
      description: ""
      example:
        status: SUCCESS
    errorResponse:
      required:
      - errorDescription
      - errorDetails
      - status
      type: object
      properties:
        status:
          type: string
          example: ERROR
        errorDescription:
          maxLength: 254
          type: string
          description: ""
        errorDetails:
          maxLength: 254
          type: string
          description: ""
      description: ""
    taskInfo:
      required:
      - createDate
      - currentStatus
      - externalId
      - typeFull
      type: object
      properties:
        createDate:
          type: string
          description: Дата создания заявки
          format: date-time
        externalId:
          maxLength: 254
          type: string
          description: Идентификатор заявки в источнике заявки (Номер КД)
        typeFull:
          maxLength: 254
          type: string
          description: Тип заявки (расшифровка)
        currentStatus:
          maxLength: 32
          type: string
          description: Текущий статус заявки
      description: Информация по заявке
      example:
        typeFull: typeFull
        currentStatus: currentStatus
        externalId: externalId
        createDate: 2000-01-23T04:56:07.000+00:00
    allTaskInfo:
      type: array
      description: Информация по всем заявкам
      items:
        $ref: '#/components/schemas/taskInfo'
    taskRequest_taskInfo:
      type: object
      properties:
        dealMembersNumber:
          $ref: '#/components/schemas/dealMembersNumber'
        client:
          $ref: '#/components/schemas/client'
        organization:
          $ref: '#/components/schemas/organization'
        estateObjects:
          type: array
          description: Объекты недвижимости
          items:
            $ref: '#/components/schemas/estateObject'

